### ISSUE TITLE
The next web (Responsive Design)

### ISSUE THREAD

**Issue by abongsjoel** [gasb150/The-next-web-responsive#2]
This isssue is for a peer-to-peer review of the code of one of the team members of team 161

**Comment by alexisbec** [comment]
It is a good practice to use the <aside> tag instead of creating a <section> or a <div> with the class "aside".

**Comment by alexisbec** [comment]
It is a good practice to use the "aside" tag instead of creating a "section" or a "div" with the class aside.

**Comment by MrkarlosM** [comment]
You have done great work so far. 

Maybe you could change the `title` page name to TNW since that's the original title of the page. 

You could use something like:

`[class*="nameclass"] {property: value;}
`
To avoid writing specific classes with similar values: son instead using:

```
.news1 {property1: value1;}

.news2 {property1: value1;}

```

You could use: 

`[class*="news"] {property1: value1;}
`

**Comment by MrkarlosM** [comment]
Also is a good practice to have a separate media query file. So you can have always a default style for the page and just change the media query one.
